package:
    name: "hello"
    version: "0.1"

source:
    path: "."

requirements:
    build:
        - python
        - setuptools

    run:
        - python

test:
    imports: "hello"

about:
    home: "https://github.com/johnlarson/hello"
